platform :ios, '7.0'

pod 'JSONKit'
pod 'AFNetworking', '1.3.1'
pod 'MWPhotoBrowser'
pod 'EGOCache', '2.0'
pod 'SVProgressHUD'
pod 'MGImageUtilities'
pod 'Objective-C-HMTL-Parser'
pod 'MagicalRecord', '2.1'
pod 'Reachability'